name: database-cluster

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: cavepostgre
    labels:
      - dev.orbstack.domains=postgre.local
    restart: always
    environment:
      POSTGRES_USER: caveman
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cave
    ports:
      - "5432:5432"
    volumes:
      - postgre-db:/var/lib/postgresql/data

  # MySQL Database
  mysql:
    image: mysql:latest
    container_name: mysql
    labels:
      - dev.orbstack.domains=mysql.local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-db:/var/lib/mysql

  # MongoDB Database
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: caveman
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  # Mongo Express UI
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: caveman
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://caveman:password@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo
    volumes:
      - mongo-express-db:/data/db

  # Adminer Database Management Web UI
  adminer:
    image: adminer:latest
    container_name: adminer
    labels:
      - dev.orbstack.domains=adminer.local
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgre-db:
  mysql-db:
  mongodb:
  mongo-express-db:
